name: pinger
description: Ping command utility app made with Flutter.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.6+2
  mobx: ^1.0.2+1
  flutter_mobx: ^1.0.1
  dotted_border: ^1.0.5
  freezed_annotation: ^0.7.1
  injectable: 0.2.3
  get_it: ^4.0.0
  fl_chart: ^0.8.2
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.4
  mobx_codegen: ^1.0.2
  json_serializable: ^3.2.5
  freezed: ^0.9.2
  injectable_generator: 0.2.3
  r_flutter: ^0.6.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
