name: pinger
description: Ping command utility app made with Flutter.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.6+1
  mobx: ^0.4.0+4
  flutter_mobx: ^0.3.6+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.3
  mobx_codegen: ^0.4.2

flutter:
  uses-material-design: true
  assets:
    - assets/