name: pinger
description: Ping command utility app made with Flutter.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.6+1
  mobx: ^0.4.0+4
  flutter_mobx: ^0.3.6+2
  dotted_border: ^1.0.4
  json_annotation: ^3.0.1
  copy_with_extension: ^1.0.7
  kiwi: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.3
  mobx_codegen: ^0.4.2
  json_serializable: ^3.2.5
  copy_with_extension_gen: ^1.0.8
  kiwi_generator:
    git: 
      url: git://github.com/tomwyr/kiwi.git
      path: kiwi_generator

flutter:
  uses-material-design: true
  assets:
    - assets/