name: release

on:
  push:
    branches: [production]
  pull_request:
    branches: [production]

jobs:
  build_and_publish_to_firebase:
    name: Publish app for release
    runs-on: macos-latest
    env:
      IS_RELEASE: true
      APP_ID: com.tomwyr.pinger
      APP_FLAVOR: prod
    steps:
      # Setup environment
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      # Build and publish Android
      # - name: Build Android
      #   env:
      #     SIGNING_KEY: ${{secrets.ANDROID_SIGNING_KEY}}
      #     SIGNING_PASSWORD: ${{secrets.ANDROID_SIGNING_PASSWORD}}
      #   run: echo $SIGNING_KEY | base64 -d > android/app/key.jks && flutter build appbundle --flavor prod
      # - name: Publish Android
      #   working-directory: ./android
      #   env:
      #     JSON_KEY_DATA: ${{secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT_KEY}}
      #   run: fastlane publish_play_store
      # Build and publish iOS
      - name: Build iOS
        run: flutter build ios --flavor prod --no-codesign
      - name: Archive iOS
        working-directory: ./ios
        env:
          GIT_URL: https://github.com/tomwyr/pinger-ios-signing.git
          KEYCHAIN_NAME: pinger-keychain
          KEYCHAIN_PASSWORD: ${{secrets.KEYCHAIN_PASSWORD}}
          MATCH_PASSWORD: ${{secrets.MATCH_PASSWORD}}
          GIT_BASIC_AUTHORIZATION: ${{secrets.GIT_BASIC_AUTHORIZATION}}
          IOS_SIGNING_IDENTITY: ${{secrets.IOS_SIGNING_IDENTITY}}
          PROFILE_TYPE: appstore
          EXPORT_METHOD: app-store
        run: fastlane sign_and_build_app
      - name: Publish iOS
        working-directory: ./ios
        run: fastlane publish_app_store
